import {mkdir, readFile, writeFile} from "node:fs/promises";

const [front, back, styling, script] = await Promise.all([
  readFile("src/front.html", "utf8"),
  readFile("src/back.html", "utf8"),
  readFile("src/styling.css", "utf8"),
  readFile("src/template.js", "utf8"),
]);

const generatedHeader = "<!-- Generated from src/. Do not edit this file directly. -->";
const withRuntime = (template) =>
  `${generatedHeader}\n${template.trim()}\n\n<script>\n${script.trim()}\n</script>\n`;

await mkdir("dist", {recursive: true});

await Promise.all([
  writeFile("dist/front.html", withRuntime(front), "utf8"),
  writeFile("dist/back.html", withRuntime(back), "utf8"),
  writeFile("dist/styling.css", `${styling.trim()}\n`, "utf8"),
]);
