import {mkdir, readFile, writeFile} from "node:fs/promises";
import path from "node:path";

const script = await readFile("src/template.js", "utf8");
const templates = [
  {
    sourceDir: "src",
    outputDir: "dist",
    cards: [{directory: "", runtimeSides: ["front", "back"]}],
  },
  {
    sourceDir: "templates/english-vocabulary",
    outputDir: "dist/english-vocabulary",
    cards: [
      {directory: "recite", runtimeSides: ["back"]},
      {directory: "spelling", runtimeSides: ["back"]},
      {directory: "dictation", runtimeSides: ["back"]},
    ],
  },
];

async function buildTemplate({sourceDir, outputDir, cards}) {
  const styling = await readFile(path.join(sourceDir, "styling.css"), "utf8");
  const generatedHeader = (directory) =>
    `<!-- Generated from ${path.join(sourceDir, directory)}/. Do not edit this file directly. -->`;
  const withRuntime = (template) =>
    `${template.header}\n${template.content.trim()}\n\n<script>\n${script.trim()}\n</script>\n`;
  const generated = (template) =>
    `${template.header}\n${template.content.trim()}\n`;

  await mkdir(outputDir, {recursive: true});
  await writeFile(
    path.join(outputDir, "styling.css"),
    `${styling.trim()}\n`,
    "utf8",
  );

  await Promise.all(
    cards.map(async ({directory, runtimeSides}) => {
      const sourceCardDir = path.join(sourceDir, directory);
      const outputCardDir = path.join(outputDir, directory);
      const [front, back] = await Promise.all([
        readFile(path.join(sourceCardDir, "front.html"), "utf8"),
        readFile(path.join(sourceCardDir, "back.html"), "utf8"),
      ]);
      const header = generatedHeader(directory);
      await mkdir(outputCardDir, {recursive: true});
      await Promise.all([
        writeFile(
          path.join(outputCardDir, "front.html"),
          (runtimeSides.includes("front") ? withRuntime : generated)({
            header,
            content: front,
          }),
          "utf8",
        ),
        writeFile(
          path.join(outputCardDir, "back.html"),
          (runtimeSides.includes("back") ? withRuntime : generated)({
            header,
            content: back,
          }),
          "utf8",
        ),
      ]);
    }),
  );
}

await Promise.all(templates.map(buildTemplate));
